name: Unit Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: "root"
          MYSQL_DATABASE: "test"
          MYSQL_USER: "test"
          MYSQL_PASSWORD: "test"
        ports:
          - "3306:3306"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

      - name: Test
        env:
          MYSQL_URI: "test:test@tcp(localhost:3306)/test?parseTime=true"
        run: go test -v ./...
